# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_atm(object):
    def setupUi(self, atm):
        atm.setObjectName("atm")
        atm.resize(500, 400)
        atm.setStyleSheet("#atm{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}\n"
"")
        self.deposit_btn = QtWidgets.QPushButton(atm)
        self.deposit_btn.setGeometry(QtCore.QRect(390, 210, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deposit_btn.setFont(font)
        self.deposit_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.deposit_btn.setObjectName("deposit_btn")
        self.pic1 = QtWidgets.QLabel(atm)
        self.pic1.setGeometry(QtCore.QRect(10, 10, 231, 51))
        self.pic1.setText("")
        self.pic1.setPixmap(QtGui.QPixmap(":/pics/pictures/pic1.png"))
        self.pic1.setObjectName("pic1")
        self.cash_btn = QtWidgets.QPushButton(atm)
        self.cash_btn.setGeometry(QtCore.QRect(390, 110, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cash_btn.setFont(font)
        self.cash_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.cash_btn.setObjectName("cash_btn")
        self.label1 = QtWidgets.QLabel(atm)
        self.label1.setGeometry(QtCore.QRect(120, 70, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.card_out_btn = QtWidgets.QPushButton(atm)
        self.card_out_btn.setGeometry(QtCore.QRect(0, 320, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.card_out_btn.setFont(font)
        self.card_out_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.card_out_btn.setObjectName("card_out_btn")
        self.transfer_btn = QtWidgets.QPushButton(atm)
        self.transfer_btn.setGeometry(QtCore.QRect(0, 110, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.transfer_btn.setFont(font)
        self.transfer_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.transfer_btn.setObjectName("transfer_btn")
        self.inquiry_btn = QtWidgets.QPushButton(atm)
        self.inquiry_btn.setGeometry(QtCore.QRect(0, 210, 111, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inquiry_btn.setFont(font)
        self.inquiry_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.inquiry_btn.setObjectName("inquiry_btn")
        self.label1_2 = QtWidgets.QLabel(atm)
        self.label1_2.setGeometry(QtCore.QRect(110, 90, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_2.sizePolicy().hasHeightForWidth())
        self.label1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label1_2.setFont(font)
        self.label1_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1_2.setScaledContents(False)
        self.label1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_2.setWordWrap(False)
        self.label1_2.setOpenExternalLinks(False)
        self.label1_2.setObjectName("label1_2")
        self.label = QtWidgets.QLabel(atm)
        self.label.setGeometry(QtCore.QRect(140, 140, 231, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pics/pictures/pic3.png"))
        self.label.setObjectName("label")

        self.retranslateUi(atm)
        QtCore.QMetaObject.connectSlotsByName(atm)

    def retranslateUi(self, atm):
        _translate = QtCore.QCoreApplication.translate
        atm.setWindowTitle(_translate("atm", "ATM"))
        self.deposit_btn.setText(_translate("atm", "存款"))
        self.cash_btn.setText(_translate("atm", "取款"))
        self.label1.setText(_translate("atm", "您好，请选择所需服务！"))
        self.card_out_btn.setText(_translate("atm", "退卡 Exit"))
        self.transfer_btn.setText(_translate("atm", "转账"))
        self.inquiry_btn.setText(_translate("atm", "查询"))
        self.label1_2.setText(_translate("atm", "Please Select Service"))
import pics_rc
