# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card_out.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_card_out(object):
    def setupUi(self, card_out):
        card_out.setObjectName("card_out")
        card_out.resize(500, 400)
        card_out.setStyleSheet("#card_out{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}")
        self.label1 = QtWidgets.QLabel(card_out)
        self.label1.setGeometry(QtCore.QRect(130, 130, 161, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(card_out)
        self.label2.setGeometry(QtCore.QRect(110, 240, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label2.setFont(font)
        self.label2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label2.setScaledContents(False)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setWordWrap(False)
        self.label2.setOpenExternalLinks(False)
        self.label2.setObjectName("label2")
        self.pic1 = QtWidgets.QLabel(card_out)
        self.pic1.setGeometry(QtCore.QRect(10, 0, 231, 51))
        self.pic1.setText("")
        self.pic1.setPixmap(QtGui.QPixmap(":/pics/pictures/pic1.png"))
        self.pic1.setObjectName("pic1")
        self.label1_2 = QtWidgets.QLabel(card_out)
        self.label1_2.setGeometry(QtCore.QRect(130, 180, 141, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_2.sizePolicy().hasHeightForWidth())
        self.label1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1_2.setFont(font)
        self.label1_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1_2.setScaledContents(False)
        self.label1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_2.setWordWrap(False)
        self.label1_2.setOpenExternalLinks(False)
        self.label1_2.setObjectName("label1_2")
        self.label_time = QtWidgets.QLabel(card_out)
        self.label_time.setGeometry(QtCore.QRect(390, 30, 71, 41))
        self.label_time.setStyleSheet("color:rgb(255, 215, 0);font-size:35px;font-weight:bold;font-family:Roman times; ")
        self.label_time.setText("")
        self.label_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")

        self.retranslateUi(card_out)
        QtCore.QMetaObject.connectSlotsByName(card_out)

    def retranslateUi(self, card_out):
        _translate = QtCore.QCoreApplication.translate
        card_out.setWindowTitle(_translate("card_out", "取卡"))
        self.label1.setText(_translate("card_out", "本次服务已结束！"))
        self.label2.setText(_translate("card_out", "请妥善保管您的个人财物！"))
        self.label1_2.setText(_translate("card_out", "感谢您的使用！"))
import pics_rc
