# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cash.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cash(object):
    def setupUi(self, cash):
        cash.setObjectName("cash")
        cash.resize(500, 400)
        cash.setStyleSheet("#cash{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}\n"
"")
        self.btn100 = QtWidgets.QPushButton(cash)
        self.btn100.setGeometry(QtCore.QRect(0, 90, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn100.setFont(font)
        self.btn100.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.btn100.setObjectName("btn100")
        self.label1_2 = QtWidgets.QLabel(cash)
        self.label1_2.setGeometry(QtCore.QRect(110, 80, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_2.sizePolicy().hasHeightForWidth())
        self.label1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label1_2.setFont(font)
        self.label1_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1_2.setScaledContents(False)
        self.label1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_2.setWordWrap(False)
        self.label1_2.setOpenExternalLinks(False)
        self.label1_2.setObjectName("label1_2")
        self.btn500 = QtWidgets.QPushButton(cash)
        self.btn500.setGeometry(QtCore.QRect(0, 160, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn500.setFont(font)
        self.btn500.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.btn500.setObjectName("btn500")
        self.label = QtWidgets.QLabel(cash)
        self.label.setGeometry(QtCore.QRect(140, 130, 231, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pics/pictures/pic3.png"))
        self.label.setObjectName("label")
        self.label1 = QtWidgets.QLabel(cash)
        self.label1.setGeometry(QtCore.QRect(120, 60, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.pic1 = QtWidgets.QLabel(cash)
        self.pic1.setGeometry(QtCore.QRect(10, 0, 231, 51))
        self.pic1.setText("")
        self.pic1.setPixmap(QtGui.QPixmap(":/pics/pictures/pic1.png"))
        self.pic1.setObjectName("pic1")
        self.card_out_btn = QtWidgets.QPushButton(cash)
        self.card_out_btn.setGeometry(QtCore.QRect(-10, 310, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.card_out_btn.setFont(font)
        self.card_out_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.card_out_btn.setObjectName("card_out_btn")
        self.btn1000 = QtWidgets.QPushButton(cash)
        self.btn1000.setGeometry(QtCore.QRect(0, 230, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn1000.setFont(font)
        self.btn1000.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.btn1000.setObjectName("btn1000")
        self.other_amount_btn = QtWidgets.QPushButton(cash)
        self.other_amount_btn.setGeometry(QtCore.QRect(390, 230, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.other_amount_btn.setFont(font)
        self.other_amount_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.other_amount_btn.setObjectName("other_amount_btn")
        self.btn5000 = QtWidgets.QPushButton(cash)
        self.btn5000.setGeometry(QtCore.QRect(390, 160, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn5000.setFont(font)
        self.btn5000.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.btn5000.setObjectName("btn5000")
        self.btn2000 = QtWidgets.QPushButton(cash)
        self.btn2000.setGeometry(QtCore.QRect(390, 90, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn2000.setFont(font)
        self.btn2000.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.btn2000.setObjectName("btn2000")
        self.return_btn = QtWidgets.QPushButton(cash)
        self.return_btn.setGeometry(QtCore.QRect(390, 310, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.return_btn.setFont(font)
        self.return_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.return_btn.setObjectName("return_btn")

        self.retranslateUi(cash)
        QtCore.QMetaObject.connectSlotsByName(cash)

    def retranslateUi(self, cash):
        _translate = QtCore.QCoreApplication.translate
        cash.setWindowTitle(_translate("cash", "取款"))
        self.btn100.setText(_translate("cash", "100"))
        self.label1_2.setText(_translate("cash", "Please Select Amount"))
        self.btn500.setText(_translate("cash", "500"))
        self.label1.setText(_translate("cash", "请选择取款金额！"))
        self.card_out_btn.setText(_translate("cash", "<- 退 卡"))
        self.btn1000.setText(_translate("cash", "1000"))
        self.other_amount_btn.setText(_translate("cash", "其他金额"))
        self.btn5000.setText(_translate("cash", "5000"))
        self.btn2000.setText(_translate("cash", "2000"))
        self.return_btn.setText(_translate("cash", "返 回 ->"))
import pics_rc
