# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manager(object):
    def setupUi(self, manager):
        manager.setObjectName("manager")
        manager.resize(500, 400)
        manager.setStyleSheet("#manager{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}")
        manager.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(manager)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(10, 310, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.exit_btn.setObjectName("exit_btn")
        self.signout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.signout_btn.setGeometry(QtCore.QRect(370, 230, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.signout_btn.setFont(font)
        self.signout_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.signout_btn.setObjectName("signout_btn")
        self.unlock_btn = QtWidgets.QPushButton(self.centralwidget)
        self.unlock_btn.setGeometry(QtCore.QRect(370, 150, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.unlock_btn.setFont(font)
        self.unlock_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.unlock_btn.setObjectName("unlock_btn")
        self.pic1 = QtWidgets.QLabel(self.centralwidget)
        self.pic1.setGeometry(QtCore.QRect(0, 0, 231, 51))
        self.pic1.setText("")
        self.pic1.setPixmap(QtGui.QPixmap(":/pics/pictures/pic1.png"))
        self.pic1.setObjectName("pic1")
        self.pic2 = QtWidgets.QLabel(self.centralwidget)
        self.pic2.setGeometry(QtCore.QRect(70, 90, 261, 211))
        self.pic2.setText("")
        self.pic2.setPixmap(QtGui.QPixmap(":/pics/pictures/pic2.jpg"))
        self.pic2.setObjectName("pic2")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(70, 50, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.signup_btn = QtWidgets.QPushButton(self.centralwidget)
        self.signup_btn.setGeometry(QtCore.QRect(370, 70, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.signup_btn.setFont(font)
        self.signup_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.signup_btn.setObjectName("signup_btn")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(370, 310, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.login_btn.setObjectName("login_btn")
        manager.setCentralWidget(self.centralwidget)


        self.retranslateUi(manager)
        self.exit_btn.clicked.connect(manager.close)
        QtCore.QMetaObject.connectSlotsByName(manager)

    def retranslateUi(self, manager):
        _translate = QtCore.QCoreApplication.translate
        manager.setWindowTitle(_translate("manager", "管理"))
        self.exit_btn.setText(_translate("manager", "退出 Exit"))
        self.signout_btn.setText(_translate("manager", "注销账户"))
        self.unlock_btn.setText(_translate("manager", "账户解锁"))
        self.label1.setText(_translate("manager", "您好，请选择您需要的服务！"))
        self.signup_btn.setText(_translate("manager", "开户"))
        self.login_btn.setText(_translate("manager", "登录 Login"))

