# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transfer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_transfer(object):
    def setupUi(self, transfer):
        transfer.setObjectName("transfer")
        transfer.resize(500, 400)
        transfer.setStyleSheet("#transfer{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}\n"
"")
        self.account = QtWidgets.QLineEdit(transfer)
        self.account.setGeometry(QtCore.QRect(160, 140, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.account.setFont(font)
        self.account.setStyleSheet("")
        self.account.setObjectName("account")
        self.label = QtWidgets.QLabel(transfer)
        self.label.setGeometry(QtCore.QRect(80, 140, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label1 = QtWidgets.QLabel(transfer)
        self.label1.setGeometry(QtCore.QRect(50, 60, 311, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.card_out_btn = QtWidgets.QPushButton(transfer)
        self.card_out_btn.setGeometry(QtCore.QRect(390, 300, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.card_out_btn.setFont(font)
        self.card_out_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.card_out_btn.setObjectName("card_out_btn")
        self.label_2 = QtWidgets.QLabel(transfer)
        self.label_2.setGeometry(QtCore.QRect(80, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pic1 = QtWidgets.QLabel(transfer)
        self.pic1.setGeometry(QtCore.QRect(20, 0, 231, 51))
        self.pic1.setText("")
        self.pic1.setPixmap(QtGui.QPixmap(":/pics/pictures/pic1.png"))
        self.pic1.setObjectName("pic1")
        self.return_btn = QtWidgets.QPushButton(transfer)
        self.return_btn.setGeometry(QtCore.QRect(-10, 300, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.return_btn.setFont(font)
        self.return_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.return_btn.setObjectName("return_btn")
        self.transfer_btn = QtWidgets.QPushButton(transfer)
        self.transfer_btn.setGeometry(QtCore.QRect(390, 220, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.transfer_btn.setFont(font)
        self.transfer_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:10px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.transfer_btn.setObjectName("transfer_btn")
        self.amount = QtWidgets.QLineEdit(transfer)

        self.amount.setGeometry(QtCore.QRect(160, 190, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.amount.setFont(font)
        self.amount.setStyleSheet("")
        self.amount.setObjectName("amount")

        self.retranslateUi(transfer)
        QtCore.QMetaObject.connectSlotsByName(transfer)

    def retranslateUi(self, transfer):
        _translate = QtCore.QCoreApplication.translate
        transfer.setWindowTitle(_translate("transfer", "Transfer"))
        self.label.setText(_translate("transfer", "账号："))
        self.label1.setText(_translate("transfer", "请输入接收方账号和转账数额！"))
        self.card_out_btn.setText(_translate("transfer", "取卡"))
        self.label_2.setText(_translate("transfer", "数额："))
        self.return_btn.setText(_translate("transfer", "返回"))
        self.transfer_btn.setText(_translate("transfer", "转账"))
import pics_rc
