# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_unlock(object):
    def setupUi(self, unlock):
        unlock.setObjectName("unlock")
        unlock.resize(500, 400)
        unlock.setStyleSheet("#unlock{background-color: rgb(52, 80, 164);border-top-left-radius:15px;border-top-right-radius:5px;border-bottom-left-radius:15px;border-bottom-right-radius:5px}\n"
"")
        self.pic1 = QtWidgets.QLabel(unlock)
        self.pic1.setGeometry(QtCore.QRect(10, 10, 231, 51))
        self.pic1.setText("")
        self.pic1.setPixmap(QtGui.QPixmap(":/pics/pictures/pic1.png"))
        self.pic1.setObjectName("pic1")
        self.label1 = QtWidgets.QLabel(unlock)
        self.label1.setGeometry(QtCore.QRect(130, 100, 271, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1.setScaledContents(False)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setWordWrap(False)
        self.label1.setOpenExternalLinks(False)
        self.label1.setObjectName("label1")
        self.return_manager_btn = QtWidgets.QPushButton(unlock)
        self.return_manager_btn.setGeometry(QtCore.QRect(10, 310, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.return_manager_btn.setFont(font)
        self.return_manager_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.return_manager_btn.setObjectName("return_manager_btn")
        self.unlock_btn = QtWidgets.QPushButton(unlock)
        self.unlock_btn.setGeometry(QtCore.QRect(360, 310, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.unlock_btn.setFont(font)
        self.unlock_btn.setStyleSheet("QPushButton{border:2px groove gray;border-radius:20px;padding:2px 4px;background-color: rgb(225, 225, 225);}\n"
"QPushButton:hover{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}\n"
"QPushButton:checked{background-color: rgb(20, 62, 134);border:none;color:rgb(255, 255, 255);}")
        self.unlock_btn.setObjectName("unlock_btn")
        self.account = QtWidgets.QLineEdit(unlock)

        self.account.setGeometry(QtCore.QRect(190, 180, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.account.setFont(font)
        self.account.setStyleSheet("")
        self.account.setObjectName("account")
        self.id = QtWidgets.QLineEdit(unlock)
        self.id.setGeometry(QtCore.QRect(190, 230, 161, 31))
        self.id.setEchoMode(QtWidgets.QLineEdit.Password)
        self.id.setObjectName("id")
        self.label_2 = QtWidgets.QLabel(unlock)
        self.label_2.setGeometry(QtCore.QRect(80, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(unlock)
        self.label.setGeometry(QtCore.QRect(110, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(unlock)
        QtCore.QMetaObject.connectSlotsByName(unlock)

    def retranslateUi(self, unlock):
        _translate = QtCore.QCoreApplication.translate
        unlock.setWindowTitle(_translate("unlock", "解锁"))
        self.label1.setText(_translate("unlock", "请输入您的账号和身份信息！"))
        self.return_manager_btn.setText(_translate("unlock", "返回"))
        self.unlock_btn.setText(_translate("unlock", "解锁"))
        self.label_2.setText(_translate("unlock", "身份证号："))
        self.label.setText(_translate("unlock", "账号："))
import pics_rc
